# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/custom-gcl.jsonschema.json

version: v2.3.0

destination: ./_tools

plugins:
  - module: 'github.com/microsoft/typescript-go/_tools'
    import: 'github.com/microsoft/typescript-go/_tools/customlint'
    path: ./_tools
