// Objective-C API for talking to github.com/microsoft/typescript-go/bridge Go package.
//   gobind -lang=objc github.com/microsoft/typescript-go/bridge
//
// File is generated by gobind. Do not edit.

#ifndef __Bridge_H__
#define __Bridge_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class BridgeBridgeDiagnostic;
@class BridgeBridgeResult;
@class BridgeBuildConfig;
@class BridgeBuildResult;
@class BridgeDiagnosticInfo;
@class BridgePathList;
@protocol BridgeFileResolver;
@class BridgeFileResolver;

@protocol BridgeFileResolver <NSObject>
/**
 * DirectoryExists returns true if the directory exists at the given path
 */
- (BOOL)directoryExists:(NSString* _Nullable)path;
/**
 * FileExists returns true if the file exists at the given path
 */
- (BOOL)fileExists:(NSString* _Nullable)path;
/**
 * ResolveFile returns the contents of the file at the given path
Returns empty string if the file doesn't exist or can't be read
 */
- (NSString* _Nonnull)resolveFile:(NSString* _Nullable)path;
/**
 * WriteFile writes content to the given path
Returns true if the write was successful
 */
- (BOOL)writeFile:(NSString* _Nullable)path content:(NSString* _Nullable)content;
@end

/**
 * BridgeDiagnostic contains detailed information about a TypeScript diagnostic (gomobile-compatible)
 */
@interface BridgeBridgeDiagnostic : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long code;
@property (nonatomic) NSString* _Nonnull category;
@property (nonatomic) NSString* _Nonnull message;
@property (nonatomic) NSString* _Nonnull file;
@property (nonatomic) long line;
@property (nonatomic) long column;
@property (nonatomic) long length;
@end

/**
 * BridgeResult contains the full result of a TypeScript compilation (gomobile-compatible)
 */
@interface BridgeBridgeResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) BOOL success;
@property (nonatomic) NSString* _Nonnull configFile;
// skipped field BridgeResult.Diagnostics with unsupported type: []github.com/microsoft/typescript-go/bridge.BridgeDiagnostic

// skipped field BridgeResult.EmittedFiles with unsupported type: []string

// skipped field BridgeResult.WrittenFiles with unsupported type: map[string]string

/**
 * GetDiagnostic returns a diagnostic by index
 */
- (BridgeBridgeDiagnostic* _Nullable)getDiagnostic:(long)index;
/**
 * GetDiagnosticCount returns the number of diagnostics
 */
- (long)getDiagnosticCount;
/**
 * GetEmittedFile returns an emitted file path by index
 */
- (NSString* _Nonnull)getEmittedFile:(long)index;
/**
 * GetEmittedFileCount returns the number of emitted files
 */
- (long)getEmittedFileCount;
/**
 * GetWrittenFileContent returns the content of a written file by path
 */
- (NSString* _Nonnull)getWrittenFileContent:(NSString* _Nullable)path;
/**
 * GetWrittenFileCount returns the number of written files
 */
- (long)getWrittenFileCount;
/**
 * GetWrittenFilePath returns a written file path by index
 */
- (NSString* _Nonnull)getWrittenFilePath:(long)index;
/**
 * GetWrittenFilePaths returns all written file paths as a PathList
 */
- (BridgePathList* _Nullable)getWrittenFilePaths;
@end

/**
 * BuildConfig holds configuration options for the build process
 */
@interface BridgeBuildConfig : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * ProjectPath is the path to the project directory or tsconfig.json file
 */
@property (nonatomic) NSString* _Nonnull projectPath;
/**
 * PrintErrors controls whether errors should be printed to stdout during compilation
 */
@property (nonatomic) BOOL printErrors;
/**
 * ConfigFile allows specifying a custom config file path (optional)
 */
@property (nonatomic) NSString* _Nonnull configFile;
/**
 * FileResolver allows providing custom file resolution (optional)
 */
@property (nonatomic) id<BridgeFileResolver> _Nullable fileResolver;
@end

/**
 * BuildResult contains the result of a TypeScript compilation
 */
@interface BridgeBuildResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * Success indicates whether the compilation succeeded
 */
@property (nonatomic) BOOL success;
// skipped field BuildResult.Diagnostics with unsupported type: []github.com/microsoft/typescript-go/bridge.DiagnosticInfo

// skipped field BuildResult.EmittedFiles with unsupported type: []string

/**
 * ConfigFile is the resolved config file path that was used
 */
@property (nonatomic) NSString* _Nonnull configFile;
// skipped field BuildResult.WrittenFiles with unsupported type: map[string]string

@end

/**
 * DiagnosticInfo contains detailed information about a TypeScript diagnostic
 */
@interface BridgeDiagnosticInfo : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * Code is the diagnostic code (e.g., 2345)
 */
@property (nonatomic) long code;
/**
 * Category is the diagnostic category (error, warning, info, etc.)
 */
@property (nonatomic) NSString* _Nonnull category;
/**
 * Message is the diagnostic message
 */
@property (nonatomic) NSString* _Nonnull message;
/**
 * File is the source file where the diagnostic occurred (may be empty)
 */
@property (nonatomic) NSString* _Nonnull file;
/**
 * Line is the line number (1-based, 0 if not available)
 */
@property (nonatomic) long line;
/**
 * Column is the column number (1-based, 0 if not available)
 */
@property (nonatomic) long column;
/**
 * Length is the length of the affected text (0 if not available)
 */
@property (nonatomic) long length;
@end

/**
 * PathList represents a list of paths for gomobile compatibility
 */
@interface BridgePathList : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field PathList.Paths with unsupported type: []string

@end

/**
 * BridgeBuildWithFileSystem builds using only the filesystem (no custom resolver)
 */
FOUNDATION_EXPORT BridgeBridgeResult* _Nullable BridgeBridgeBuildWithFileSystem(NSString* _Nullable projectPath, BOOL printErrors, NSString* _Nullable configFile, NSError* _Nullable* _Nullable error);

// skipped function BuildWithConfig with unsupported parameter or return types


/**
 * BuildWithFileResolver builds with a dynamic callback-based file resolver
 */
FOUNDATION_EXPORT BridgeBridgeResult* _Nullable BridgeBuildWithFileResolver(NSString* _Nullable projectPath, BOOL printErrors, NSString* _Nullable configFile, id<BridgeFileResolver> _Nullable resolver, NSError* _Nullable* _Nullable error);

@class BridgeFileResolver;

/**
 * FileResolver is the interface that Swift can implement to provide custom file resolution
 */
@interface BridgeFileResolver : NSObject <goSeqRefInterface, BridgeFileResolver> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * DirectoryExists returns true if the directory exists at the given path
 */
- (BOOL)directoryExists:(NSString* _Nullable)path;
/**
 * FileExists returns true if the file exists at the given path
 */
- (BOOL)fileExists:(NSString* _Nullable)path;
/**
 * ResolveFile returns the contents of the file at the given path
Returns empty string if the file doesn't exist or can't be read
 */
- (NSString* _Nonnull)resolveFile:(NSString* _Nullable)path;
/**
 * WriteFile writes content to the given path
Returns true if the write was successful
 */
- (BOOL)writeFile:(NSString* _Nullable)path content:(NSString* _Nullable)content;
@end

#endif
