name: Create CI cache

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    # Run every day at 10:00 UTC / 03:00 PST
    - cron: '0 10 * * *'

permissions:
  contents: read

# Ensure scripts are run with pipefail. See:
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
defaults:
  run:
    shell: bash

jobs:
  cache:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        go-version:
          - '>=1.24.0'

        include:
          # Temporary for the Copilot setup steps
          - os: ubuntu-latest
            go-version: '>=1.25.0-rc.1'

    runs-on: ${{ matrix.os }}

    steps:
      - run: git config --system core.longpaths true
        if: ${{ matrix.os == 'windows-latest' }}

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      - uses: dtolnay/rust-toolchain@fcf085fcb4b4b8f63f96906cd713eb52181b5ea4 # stable

      - uses: ./.github/actions/setup-go
        with:
          go-version: ${{ matrix.go-version }}
          create: 'true'
