// Objective-C API for talking to github.com/microsoft/typescript-go/bridge Go package.
//   gobind -lang=objc github.com/microsoft/typescript-go/bridge
//
// File is generated by gobind. Do not edit.

#ifndef __Bridge_H__
#define __Bridge_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT BOOL BridgeBuild(NSString* _Nullable configPath, NSError* _Nullable* _Nullable error);

#endif
