
// Objective-C API for talking to the following Go packages
//
//	github.com/microsoft/typescript-go/bridge
//
// File is generated by gomobile bind. Do not edit.
#ifndef __TSGoBindings_FRAMEWORK_H__
#define __TSGoBindings_FRAMEWORK_H__

#include "Bridge.objc.h"
#include "Universe.objc.h"

#endif
